name: 'build'

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

concurrency: nope
permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        run: pipx run zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-installer:
    runs-on: windows-${{ matrix.image }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: CLANGARM64
            arch_name: arm64
            image: 11-arm
          - msystem: CLANG64
            arch_name: x86_64
            image: 2022
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: setup-msys2
        uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        env:
          __SETUP_MSYS2_USE_MAIN_MIRROR_ONLY: 'true'
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            tar
          pacboy: >-
            qt-installer-framework:p
            7zip:p

      - name: Build Installer
        shell: msys2 {0}
        run: |
          bash make-msys2-installer

      - name: Create 'latest' Variants
        shell: msys2 {0}
        run: |
          mv msys2-${{ matrix.arch_name }}-[0-9]*.exe msys2-${{ matrix.arch_name }}-latest.exe.unsigned
          if [ "${{ matrix.arch_name }}" != "arm64" ]; then
            mv msys2-base-${{ matrix.arch_name }}-[0-9]*.sfx.exe msys2-base-${{ matrix.arch_name }}-latest.sfx.exe.unsigned
            mv msys2-*.tar.xz msys2-base-${{ matrix.arch_name }}-latest.tar.xz
            mv msys2-*.tar.zst msys2-base-${{ matrix.arch_name }}-latest.tar.zst
          fi
          mv msys2-*.packages.txt msys2-base-${{ matrix.arch_name }}-latest.packages.txt
          { printf 'SHA-256 Filename\n- -\n' && sha256sum msys2-*; } | sed 's/^\([^ ]*\) \(.*\)/|\1|\2|/' > "$GITHUB_STEP_SUMMARY"

      - name: Upload Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: installer-${{ matrix.arch_name }}
          path: msys2-*

  sign-installer:
    runs-on: ubuntu-24.04
    needs:
      - build-installer
      - zizmor
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    environment:
      name: sign-env
      deployment: false
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-x86_64

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-arm64

      - name: Download aas-sign
        env:
          AAS_SIGN_VERSION: 1.1.0
          AAS_SIGN_CHECKSUM: 7c7d2b155a910b8144ea45ea1f7bda12afe6d749c9477b6d3c20321308e0e9f8
        run: |
          # FIXME: build this ourselves to avoid depending on a third party binary
          curl \
            --fail \
            --silent \
            --show-error \
            --location \
            --output aas-sign \
            "https://github.com/skeeto/aas-sign/releases/download/v${AAS_SIGN_VERSION}/aas-sign-linux-x86_64"
          echo "${AAS_SIGN_CHECKSUM}  aas-sign" | sha256sum --check
          chmod +x aas-sign

      - name: Sign Installers
        env:
          # None are really secret, but can't hurt to not expose all these publicly
          AZURE_SIGNING_ENDPOINT: ${{ secrets.AZURE_SIGNING_ENDPOINT }}
          AZURE_SIGNING_ACCOUNT: ${{ secrets.AZURE_SIGNING_ACCOUNT }}
          AZURE_SIGNING_PROFILE: ${{ secrets.AZURE_SIGNING_PROFILE }}
          AZURE_SIGNING_CLIENT_ID: ${{ secrets.AZURE_SIGNING_CLIENT_ID }}
          AZURE_SIGNING_TENANT_ID: ${{ secrets.AZURE_SIGNING_TENANT_ID }}
        run: |
          for f in *.exe.unsigned; do mv "$f" "${f%.exe.unsigned}.exe"; done
          ./aas-sign sign \
            --endpoint "${AZURE_SIGNING_ENDPOINT}" \
            --account "${AZURE_SIGNING_ACCOUNT}" \
            --profile "${AZURE_SIGNING_PROFILE}" \
            --oidc-client-id "${AZURE_SIGNING_CLIENT_ID}" \
            --oidc-tenant-id "${AZURE_SIGNING_TENANT_ID}" \
            *.exe
          { printf 'SHA-256 Filename\n- -\n' && sha256sum *.exe; } | sed 's/^\([^ ]*\) \(.*\)/|\1|\2|/' > "$GITHUB_STEP_SUMMARY"

      - name: Upload Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: installer-signed
          path: '*.exe'

  after-sign:
    runs-on: ubuntu-24.04
    needs:
      - build-installer
      - sign-installer
    # This only exists for PRs, since we can't depend on sign-installer for PRs.
    # In theory it could be merged into "sign-installer" with some "if", but I'd like
    # to keep the signing job simple.
    if: ${{ !(failure() || cancelled()) }}
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: github.ref != 'refs/heads/main'
        with:
          name: installer-x86_64

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: github.ref != 'refs/heads/main'
        with:
          name: installer-arm64

      - name: Rename Installers
        if: github.ref != 'refs/heads/main'
        run: |
          for f in *.exe.unsigned; do mv "$f" "${f%.exe.unsigned}.exe"; done

      - name: Upload Results
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: installer-signed
          path: '*.exe'

  test-installer:
    name: installer-${{ matrix.image }}
    runs-on: windows-${{ matrix.image }}
    needs: after-sign
    if: ${{ !(failure() || cancelled()) }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_name: arm64
            image: 11-arm
          - arch_name: x86_64
            image: 2022
          - arch_name: x86_64
            image: 2025
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-signed

      - name: Install
        run: |
          ./msys2-${{ matrix.arch_name }}-latest.exe in --confirm-command --accept-messages --root C:/msys2-install-test

      - name: Test without Login Shell
        run: |
          C:\msys2-install-test\usr\bin\pacman.exe -Syy
          C:\msys2-install-test\usr\bin\pacman.exe --noconfirm -S vim

      - name: Test
        run: |
          C:\msys2-install-test\usr\bin\bash.exe -lc "pacman --version"
          C:\msys2-install-test\usr\bin\bash.exe -lc "pacman -Qkv"
          C:\msys2-install-test\usr\bin\bash.exe -lc "pacman -Syy"
          C:\msys2-install-test\usr\bin\bash.exe -lc "pacman --noconfirm -S git"

      - name: Uninstall
        run: |
          C:\msys2-install-test\uninstall.exe pr --confirm-command

  test-docker-sfx:
    name: docker-sfx-${{ matrix.image }}
    runs-on: windows-${{ matrix.image }}
    needs: after-sign
    if: ${{ !(failure() || cancelled()) }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image: [2022, 2025]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-signed

      # https://github.com/actions/runner-images/issues/13729
      - name: Docker issue workaround
        run: |
          $dockerState = Get-Service -Name "docker"
          if ($dockerState.Status -ne "Running") {
            Start-Service -Name "docker"
          }

      - name: Build image
        run: |
          docker build -t msys2-base -f ./.ci/Dockerfile.${{ matrix.image }} .

      - name: Test without Login Shell
        run: |
          docker run msys2-base C:\msys64\usr\bin\pacman.exe -Syy
          docker run msys2-base C:\msys64\usr\bin\pacman.exe --noconfirm -S vim

      - name: Test
        run: |
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman --version"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Qkv"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Qkk || true"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Syy"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm git"

  test-sfx:
    name: sfx-${{ matrix.image }}
    runs-on: windows-${{ matrix.image }}
    needs: after-sign
    if: ${{ !(failure() || cancelled()) }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_name: x86_64
            image: 11-arm
          - arch_name: x86_64
            image: 2022
          - arch_name: x86_64
            image: 2025
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-signed

      - name: Install
        run: |
          ./msys2-base-${{ matrix.arch_name }}-latest.sfx.exe  -y -oC:/msys2-install-test

      - name: Test without Login Shell
        run: |
          $env:Path = 'C:\msys2-install-test\msys64\usr\bin;' + $env:Path
          C:\msys2-install-test\msys64\usr\bin\bash.exe -c "pacman-key --init"
          C:\msys2-install-test\msys64\usr\bin\bash.exe -c "pacman-key --populate"
          C:\msys2-install-test\msys64\usr\bin\bash.exe -c "pacman -Syy"
          C:\msys2-install-test\msys64\usr\bin\bash.exe -c "pacman --noconfirm -S vim"

      - name: Test
        run: |
          C:\msys2-install-test\msys64\usr\bin\bash.exe -lc "pacman --version"
          C:\msys2-install-test\msys64\usr\bin\bash.exe -lc "pacman -Qkv"
          C:\msys2-install-test\msys64\usr\bin\bash.exe -lc "pacman -Qkk || true"
          C:\msys2-install-test\msys64\usr\bin\bash.exe -lc "pacman -Syy"
          C:\msys2-install-test\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm git"

  verify-signed:
    runs-on: ubuntu-24.04
    needs: sign-installer
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install osslsigncode
        run: sudo apt-get install -y osslsigncode

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-signed

      - name: Verify Signatures
        run: |
          FILES=(msys2-base-x86_64-latest.sfx.exe msys2-x86_64-latest.exe msys2-arm64-latest.exe)
          curl --fail -o \
              "msft.crt" \
              "https://www.microsoft.com/pkiops/certs/Microsoft%20Identity%20Verification%20Root%20Certificate%20Authority%202020.crt"
          openssl x509 -inform DER -in "msft.crt" -out "msft.pem"
          ARGS=(verify -CAfile "msft.pem" -TSA-CAfile "msft.pem")
          for FILE in "${FILES[@]}"; do
              osslsigncode "${ARGS[@]}" -in "$FILE"
              osslsigncode "${ARGS[@]}" -time "$(date -d "+366 days" +%s)" -in "$FILE"
          done

  upload-nightly:
    permissions:
      contents: write
    needs:
      - zizmor
      - test-docker-sfx
      - test-installer
      - test-sfx
      - sign-installer
      - verify-signed
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-x86_64

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-arm64

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: installer-signed

      - name: Upload Installers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -f *.exe.unsigned
          export DO_NOT_TRACK=true
          gh release upload nightly-x86_64 msys2-* --clobber -R ${{ github.repository }}
